"""add_rfid

Revision ID: 057c0fdcdc93
Revises: 48d64df1da5d
Create Date: 2022-09-14 06:33:12.181464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '057c0fdcdc93'
down_revision = '48d64df1da5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfids',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('item_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('item_type', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_foreign_key(None, 'farm_fertilizers', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'farm_trees', 'users', ['updated_by'], ['id'])
    op.alter_column('item_resources', 'item_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'item_resources', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_resources', type_='foreignkey')
    op.alter_column('item_resources', 'item_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint(None, 'farm_trees', type_='foreignkey')
    op.drop_constraint(None, 'farm_fertilizers', type_='foreignkey')
    op.drop_table('rfids')
    # ### end Alembic commands ###
