"""update_by

Revision ID: 301e9d3187db
Revises: 151d5055bd47
Create Date: 2022-09-09 02:23:19.123460

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '301e9d3187db'
down_revision = '151d5055bd47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'resource', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'role', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    # ### end Alembic commands ###
