"""update_resource

Revision ID: 48d64df1da5d
Revises: a9a112dc061d
Create Date: 2022-09-13 07:28:32.285334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48d64df1da5d'
down_revision = 'a9a112dc061d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'file_size',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint('farms_name_key', 'farms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'file_size',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
    op.create_unique_constraint('farms_name_key', 'farms', ['name'])
    # ### end Alembic commands ###
