"""add_item_resources

Revision ID: a9a112dc061d
Revises: da3b2aec3366
Create Date: 2022-09-13 03:14:25.277113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9a112dc061d'
down_revision = 'da3b2aec3366'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_resources',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.String(length=255), nullable=True),
    sa.Column('item_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'],),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_resources')
    # ### end Alembic commands ###
