"""add_product_request_status

Revision ID: b554b4fdead7
Revises: b58a015b124f
Create Date: 2022-09-26 07:51:02.078485

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b554b4fdead7'
down_revision = 'b58a015b124f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_transfer_status',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('product_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('transfer_status', sa.String(length=255), nullable=True),
    sa.Column('updated_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),   
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ), 
    sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('users', sa.Column('firebase_register_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_transfer_status')
    op.drop_column('users', 'firebase_register_token')
    # ### end Alembic commands ###
