"""add_farm_fertilizer_tree_relationships

Revision ID: da3b2aec3366
Revises: 7d9bc467d661
Create Date: 2022-09-13 02:35:12.800870

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'da3b2aec3366'
down_revision = '7d9bc467d661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_fertilizers',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('farm_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('fertilizer_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('updated_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),    
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ), 
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('farm_trees',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('farm_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('tree_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('updated_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),    
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ), 
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm_fertilizers')
    op.drop_table('farm_trees')
    # ### end Alembic commands ###
